{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{include file="field_input.tpl" field=$downloads_per_cron}}
<div class="submit"><input type="submit" name="page_site" value="{{$submit}}"></div>

