{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<div class="mailstream-item-body">{{$item.body}}</div>
{{if $item.plink}}
<a class="mailstream-item-plink" href="{{$item.plink}}">{{$item.plink}}</a>
{{/if}}
